name: Test Basic Bioinformatics GraphQL API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_run_API:
    name: Build env and run the API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    
    steps:
      - name: Run code checkout action
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda env create -f environment.yml
          conda info         
          $CONDA/bin/activate GraphQL_API_in_Bioinformatics

      - name: Serve the API
        run: |
          # pip install flask==2.1.3 ariadne==0.15.1
          python3 main.py &
          sleep 2

      - name: Run the pytest
        run: |
          pip install pytest requests
          curl 'http://localhost:5000/graphql' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:5000' --data-binary '{"query":"query {\n  expression_profiles(transcript_id: \"TranscriptID2.1\"){\n    transcript_id\n  }\n}"}' --compressed
          pytest tests/
