name: Demo Advanced Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build_and_run_API:
    name: Build env and run the API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    
    steps:
      - name: Run code checkout action
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda env create -f environment.yml
          conda activate GraphQL_API_in_Bioinformatics

      - name: Run the API
        run: |
          python3 main.py

      - name: Test with pytest
        run: |
          pip install pytest requests
          pytest tests/
